{
 "title": "nestjs-template dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Http Server Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Average response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(http_server_request_duration_sum{service=\"nestjs-template\"}[5m])\n/\nrate(http_server_request_duration_count{service=\"nestjs-template\"}[5m])",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_count{service=\"nestjs-template\"}[1m])) by (service)",
     "legendFormat": "total requests rate"
    },
    {
     "expr": "sum(rate(http_server_request_duration_count{http_response_status_code=\"500\", service=\"nestjs-template\"}[1m])) by (service)",
     "legendFormat": "error responses rate"
    }
   ]
  },
  {
   "title": "Historic P90 response time by endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_server_request_duration_bucket{service=\"nestjs-template\"}[1m])) by (le, http_request_method, http_route))",
     "legendFormat": "{{http_request_method}}#{{http_route}}"
    }
   ]
  },
  {
   "title": "Throughput by status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_count{service=\"nestjs-template\"}[1m])) by (http_response_status_code)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "HTTP Responses by method and status code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (http_response_status_code, http_request_method) (increase(http_server_request_duration_count{service=\"nestjs-template\"}[$__rate_interval]))",
     "legendFormat": "{{http_request_method}}: {{http_response_status_code}} status"
    }
   ]
  },
  {
   "title": "Probe Error Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_count{service=\"nestjs-template\", http_response_status_code=~\"[45]..\"}[1m])) by (service) / sum(rate(http_server_request_duration_count{service=\"nestjs-template\"}[1m])) by (service)",
     "legendFormat": "error ratio"
    }
   ]
  },
  { "title": "Http Client Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Average response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(http_client_request_duration_sum{service=\"nestjs-template\"}[5m])\n/\nrate(http_client_request_duration_count{service=\"nestjs-template\"}[5m])",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_client_request_duration_count{service=\"nestjs-template\"}[1m])) by (service)",
     "legendFormat": "total requests rate"
    },
    {
     "expr": "sum(rate(http_client_request_duration_count{http_response_status_code=\"500\", service=\"nestjs-template\"}[1m])) by (service)",
     "legendFormat": "error responses rate"
    }
   ]
  },
  {
   "title": "Throughput by status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_client_request_duration_count{service=\"nestjs-template\"}[1m])) by (http_response_status_code)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Historic P90 response time by endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_client_request_duration_bucket{service=\"nestjs-template\"}[1m])) by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_client_request_duration_bucket{service=\"nestjs-template\"}[1m])) by (le))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_client_request_duration_bucket{service=\"nestjs-template\"}[1m])) by (le))",
     "legendFormat": "P50"
    }
   ]
  }
 ]
}